version: '3.8'

services:
  # Redis for Celery broker and result backend
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - beer_crawl_network

  # PostgreSQL database
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: beer_crawl
      POSTGRES_USER: beer_crawl_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beer_crawl_user -d beer_crawl"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - beer_crawl_network

  # Main Flask application
  web:
    image: ghcr.io/your-username/beer-crawl:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://beer_crawl_user:$(cat /run/secrets/db_password)@postgres:5432/beer_crawl
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - API_BASE_URL=https://your-domain.com
      - SECRET_KEY_FILE=/run/secrets/flask_secret_key
      - WHATSAPP_TOKEN_FILE=/run/secrets/whatsapp_token
      - FLASK_DEBUG=false
    volumes:
      - ./logs:/app/logs
    secrets:
      - flask_secret_key
      - whatsapp_token
      - db_password
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - beer_crawl_network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Celery worker
  worker:
    image: ghcr.io/your-username/beer-crawl:latest
    restart: unless-stopped
    command: celery -A src.tasks.celery_tasks.celery worker --loglevel=info --concurrency=4
    environment:
      - DATABASE_URL=postgresql://beer_crawl_user:$(cat /run/secrets/db_password)@postgres:5432/beer_crawl
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - API_BASE_URL=https://your-domain.com
      - SECRET_KEY_FILE=/run/secrets/flask_secret_key
      - WHATSAPP_TOKEN_FILE=/run/secrets/whatsapp_token
    volumes:
      - ./logs:/app/logs
    secrets:
      - flask_secret_key
      - whatsapp_token
      - db_password
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - beer_crawl_network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Celery beat scheduler
  beat:
    image: ghcr.io/your-username/beer-crawl:latest
    restart: unless-stopped
    command: celery -A src.tasks.celery_tasks.celery beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://beer_crawl_user:$(cat /run/secrets/db_password)@postgres:5432/beer_crawl
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - API_BASE_URL=https://your-domain.com
      - SECRET_KEY_FILE=/run/secrets/flask_secret_key
    volumes:
      - ./logs:/app/logs
    secrets:
      - flask_secret_key
      - db_password
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - beer_crawl_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web
    networks:
      - beer_crawl_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  # Monitoring with Flower (optional)
  flower:
    image: ghcr.io/your-username/beer-crawl:latest
    restart: unless-stopped
    command: celery -A src.tasks.celery_tasks.celery flower --port=5555 --url_prefix=flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_BASIC_AUTH=admin:$(cat /run/secrets/flower_password)
    secrets:
      - flower_password
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - beer_crawl_network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 128M

secrets:
  flask_secret_key:
    external: true
  whatsapp_token:
    external: true
  db_password:
    external: true
  flower_password:
    external: true

volumes:
  redis_data:
  postgres_data:

networks:
  beer_crawl_network:
    driver: overlay
    attachable: true
